spring:
  application:
    name:  TOMTOM_ECOMMERCE
  datasource:
    url: jdbc:mysql://localhost:3306/tomtom
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update